version: '3.7'

services:
  run_tests:
    #image: python:3.11-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "ls -la && pytest -v -s --reruns=3 -n=5 --alluredir allure-results"
    working_dir: /usr/workspace
    environment:
      - USERNAME=${USERNAME}
      - API_TOKEN=${API_TOKEN}
