name: Tests memes API

on: workflow_dispatch

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run API-tests via docker-compose
        env:
          USERNAME: ${{ vars.USERNAME }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          docker compose up --exit-code-from run_tests || true

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history  # Создает директорию для истории Allure
          sudo cp -R ./.github/gh-pages/history/* allure-results/history/
        continue-on-error: true

      - name: Generate Allure report
        run: |
          sudo docker compose run run_tests /bin/sh -c "allure generate -c allure-results -o allure-report"

      - name: Update Allure history
        run: |
          sudo cp -R allure-report/history/* ./.github/gh-pages/history/
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
